# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-05-23 19:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20191125_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2020, 5, 23, 22, 8, 6, 142425), verbose_name='Дата комментария'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 23, 22, 8, 6, 142425), verbose_name='Опубликована:'),
        ),
    ]
