# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-05-23 19:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20200523_2208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total',
            new_name='size',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='qty',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='size',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2020, 5, 23, 22, 30, 2, 923900), verbose_name='Дата комментария'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 23, 22, 30, 2, 922899), verbose_name='Опубликована:'),
        ),
    ]
