# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-05-23 19:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20200523_2230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='size',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='qty',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2020, 5, 23, 22, 31, 56, 202082), verbose_name='Дата комментария'),
        ),
        migrations.AlterField(
            model_name='order',
            name='size',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 23, 22, 31, 56, 201081), verbose_name='Опубликована:'),
        ),
    ]
